export enum MovimentoStatus {
  CRIADO = 'CRIADO',
  ATUALIZADO = 'ATUALIZADO',
  EM_ANALISE = 'EM_ANALISE',
  EM_DESENVOLVIMENTO = 'EM_DESENVOLVIMENTO',
  EM_TESTE = 'EM_TESTE',
  AGUARDANDO_CLIENTE = 'AGUARDANDO_CLIENTE',
  AGUARDANDO_TERCEIROS = 'AGUARDANDO_TERCEIROS',
  CONCLUIDO = 'CONCLUIDO',
  CANCELADO = 'CANCELADO'
}
